travis:
  secure:
    BINSTAR_TOKEN: YrBIh4Jbf2sGxSKwdPOCouI23KSXWtIoj+Nr53V6x+tEacTgsbKUvoGAzI+eKF6G8HC8zIp5v8Lw2VvDOzhnLjS2JWSKMGjD9duNQnwKGtwh6xp7g1lbClMW5uNjpAxFylLibhu9m4aOjEsWJYrVXdMgGBArfmzAHl7gl6my3IM+Y3S7QPa5mv8RWz5sIdwO1Yp926hnZUQPQNuOmu4g79Co/f8S50tgICtgQA2UkFQIt6tVidn5tGSwxHULHWuPHR6inRKBuIiq0vjfxF8RXOEC0yok7+HLQL/ODb45ELJXOqtA57+E77JAm8gn+SCmGPxDeWk46ua18AG4Nv1+ChH979LEq4ndWq1PdCWy9il46Q4bYKJ5/JCblSF8MQlnX40kxh4XohcSUNFYcJw3uLORkbUi5UZzI/efjv8dABh+Twh4jSZREbKAtaIB/L2SUpUCNzm2S+cdWZrOoir7im8OhDJ+ta/PXCv4m2rka+YNW4oItQflurZCC6Fyf4Ja9waE5No/ABZT+u78Ls+GrEbL9HIksr8qdtn8w9xO9VUBUQ1p13ApabT8vYXukaEA7hiIrA1kt7Ulr3wgWNNGrdflQHhHcOR2qloQxfz7f7WcLmlwSlNKno7SqzAGpG18Kx15PPl9KvjGpXnCX4xyNJT0sW75ELYxODNuUyLj5yo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
