travis:
  secure:
    BINSTAR_TOKEN: SU+vme93zQrAw/qTUSl3RUzGuPprm+Xk9uDBsvaPBsdy1zCPrPKIj5L8Lix08xWyL8vbFRHGKZl1r09BHfXkDiP0ACZGl/0bMZlM3X5ESE/PtW/L4bnYOziqWBStwVdZFX0ud+1if3UIibFSdNxqceg5c3jauO4Pi71U+EU/r72C45ERQWxFEY34gi6/8P23d1wnqnL5k/Lb0zCaZgzE58S6VUmOrxpofBmF4CTc/3b1wp6UpctMK9t9V3zI6WXUPyIhEvy4ECjz1rIapIOshLDwr9mpEPExHLd4EGdGWFaMtkKSF6NDd9ExWQ4caaSUhmsCQmiLN6WCNxTn8CwITlXI6oEbv3In9+uMxTjL6erTnmb5xlN4PiRZWZNb4Kwu/BR2x9SjeJGMT7PiHR1KzdxdEYnuTsDbt/zswDkFFYwYQXANaxTUqodov8e68g4cRVL5co9CBIbHp68QQ6z5GBQnOEhHVokN+QG0A2gE+bus97MG0GkMAWum/BSdWSgLM2v9eKjQG0DdD7awXODQZptxKvnRxmGLLKJQ4p3lUUP+ugFcwksCofb9orZ6Rcha8LkBuNqWDwt59eXuo6Xxl5dCit3Qg3R3eO3EUnM8fB0+fTld88FK9e4Lv7VIMlJ3iiRxZe9nAPfmH9evHyDKbHy6mJG45HBD62wDKkOY/xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
